/**
 * Wedding Element Presets
 * Pre-configured Fabric.js objects for common wedding invitation elements
 */
import { generateObjectId } from "./fabric-helpers";

// Curated wedding color palettes
export const COLOR_PALETTES = {
  "luxury-dark": {
    label: "Luxury Dark",
    colors: { bg: "#111612", fg: "#F5F2EA", primary: "#D8D0BD", accent: "#C8B58A", muted: "#879181" },
  },
  "soft-blush": {
    label: "Soft Blush",
    colors: { bg: "#FFF5F5", fg: "#2D1810", primary: "#E8B4B8", accent: "#D4A574", muted: "#C9B8A8" },
  },
  "garden-sage": {
    label: "Garden Sage",
    colors: { bg: "#F5F7F0", fg: "#1A2E1A", primary: "#6B8F71", accent: "#D4AF37", muted: "#A8B89A" },
  },
  "midnight-gold": {
    label: "Midnight Gold",
    colors: { bg: "#0A0E1A", fg: "#F0EDE5", primary: "#D4AF37", accent: "#B8860B", muted: "#6B7280" },
  },
  "ocean-breeze": {
    label: "Ocean Breeze",
    colors: { bg: "#F0F9FF", fg: "#0C2340", primary: "#2563EB", accent: "#7DD3FC", muted: "#94A3B8" },
  },
  "rustic-warm": {
    label: "Rustic Warm",
    colors: { bg: "#FBF7F0", fg: "#3D2B1F", primary: "#8B6914", accent: "#C8956E", muted: "#B5A18E" },
  },
};

// Element preset definitions
export interface ElementPreset {
  type: string;
  label: string;
  icon: string;
  category: "text" | "shape" | "media" | "decorative" | "wedding";
  create: (canvasWidth: number, canvasHeight: number) => any; // Returns fabric object config
}

// Helper to create a text object config
function textConfig(
  overrides: Record<string, any>,
  canvasWidth: number
) {
  return {
    type: "Textbox",
    id: generateObjectId("text"),
    left: canvasWidth / 2 - 150,
    top: 100,
    width: 300,
    fontSize: 24,
    fontFamily: "Cormorant Garamond",
    fill: "#F5F2EA",
    textAlign: "center",
    editable: true,
    ...overrides,
  };
}

export const ELEMENT_PRESETS: ElementPreset[] = [
  // ── Text Elements ──
  {
    type: "heading",
    label: "Heading",
    icon: "H",
    category: "text",
    create: (w) =>
      textConfig(
        {
          name: "Heading",
          text: "THE WEDDING OF",
          fontSize: 14,
          fontFamily: "DM Sans",
          letterSpacing: 600,
          charSpacing: 600,
          fontWeight: "400",
          fill: "#C8B58A",
        },
        w
      ),
  },
  {
    type: "title",
    label: "Title / Nama",
    icon: "T",
    category: "text",
    create: (w) =>
      textConfig(
        {
          name: "Title",
          text: "Aral & Patricia",
          fontSize: 48,
          fontFamily: "Cormorant Garamond",
          fontWeight: "400",
          fill: "#F5F2EA",
        },
        w
      ),
  },
  {
    type: "subtitle",
    label: "Subtitle",
    icon: "S",
    category: "text",
    create: (w) =>
      textConfig(
        {
          name: "Subtitle",
          text: "24 . 08 . 2026",
          fontSize: 16,
          fontFamily: "DM Sans",
          fontWeight: "300",
          fill: "#D8D0BD",
          charSpacing: 300,
        },
        w
      ),
  },
  {
    type: "body",
    label: "Body Text",
    icon: "¶",
    category: "text",
    create: (w) =>
      textConfig(
        {
          name: "Body Text",
          text: "We invite you to share in our joy as we celebrate our union in love.",
          fontSize: 14,
          fontFamily: "DM Sans",
          fontWeight: "300",
          fill: "#A8AEA4",
          lineHeight: 1.6,
          width: 340,
          left: w / 2 - 170,
        },
        w
      ),
  },
  {
    type: "label",
    label: "Label",
    icon: "L",
    category: "text",
    create: (w) =>
      textConfig(
        {
          name: "Label",
          text: "CEREMONY",
          fontSize: 11,
          fontFamily: "DM Sans",
          fontWeight: "500",
          fill: "#C8B58A",
          charSpacing: 400,
        },
        w
      ),
  },

  // ── Shape Elements ──
  {
    type: "rectangle",
    label: "Rectangle",
    icon: "▭",
    category: "shape",
    create: (w, h) => ({
      type: "Rect",
      id: generateObjectId("rect"),
      name: "Rectangle",
      left: w / 2 - 100,
      top: h / 2 - 50,
      width: 200,
      height: 100,
      fill: "rgba(255,255,255,0.08)",
      stroke: "rgba(255,255,255,0.2)",
      strokeWidth: 1,
      rx: 8,
      ry: 8,
    }),
  },
  {
    type: "circle",
    label: "Circle",
    icon: "○",
    category: "shape",
    create: (w, h) => ({
      type: "Circle",
      id: generateObjectId("circle"),
      name: "Circle",
      left: w / 2 - 50,
      top: h / 2 - 50,
      radius: 50,
      fill: "rgba(255,255,255,0.08)",
      stroke: "rgba(255,255,255,0.2)",
      strokeWidth: 1,
    }),
  },
  {
    type: "line",
    label: "Line / Divider",
    icon: "─",
    category: "shape",
    create: (w, h) => ({
      type: "Line",
      id: generateObjectId("line"),
      name: "Divider",
      x1: w / 2 - 80,
      y1: h / 2,
      x2: w / 2 + 80,
      y2: h / 2,
      stroke: "#C8B58A",
      strokeWidth: 1,
    }),
  },
  {
    type: "overlay",
    label: "Overlay / Gradient",
    icon: "◧",
    category: "shape",
    create: (w, h) => ({
      type: "Rect",
      id: generateObjectId("overlay"),
      name: "Overlay",
      left: 0,
      top: 0,
      width: w,
      height: h,
      fill: "rgba(0,0,0,0.45)",
      selectable: true,
      evented: true,
    }),
  },

  // ── Media Elements ──
  {
    type: "image",
    label: "Image",
    icon: "🖼",
    category: "media",
    create: (w, h) => ({
      type: "Rect", // Placeholder — actual image loaded via fabric.Image.fromURL
      id: generateObjectId("img"),
      name: "Image Placeholder",
      left: w / 2 - 75,
      top: h / 2 - 75,
      width: 150,
      height: 150,
      fill: "rgba(200,181,138,0.15)",
      stroke: "rgba(200,181,138,0.4)",
      strokeWidth: 1,
      strokeDashArray: [8, 4],
      rx: 8,
      ry: 8,
      data: { isImagePlaceholder: true },
    }),
  },

  // ── Decorative Elements ──
  {
    type: "ornament-line",
    label: "Ornament Line",
    icon: "✦",
    category: "decorative",
    create: (w, h) => ({
      type: "Textbox",
      id: generateObjectId("ornament"),
      name: "Ornament",
      text: "─── ✦ ───",
      left: w / 2 - 100,
      top: h / 2,
      width: 200,
      fontSize: 16,
      fontFamily: "serif",
      fill: "#C8B58A",
      textAlign: "center",
      editable: false,
    }),
  },
  {
    type: "floral-corner",
    label: "Decorative Text",
    icon: "❀",
    category: "decorative",
    create: (w) => ({
      type: "Textbox",
      id: generateObjectId("deco"),
      name: "Decorative Text",
      text: "❀",
      left: 20,
      top: 20,
      width: 60,
      fontSize: 40,
      fill: "#C8B58A",
      textAlign: "center",
      opacity: 0.6,
    }),
  },

  // ── Wedding Section Presets ──
  {
    type: "cover-section",
    label: "Cover Section",
    icon: "📜",
    category: "wedding",
    create: (w, h) => ({
      type: "Group",
      id: generateObjectId("cover"),
      name: "Cover Section",
      _isPresetGroup: true,
      _children: [
        {
          type: "Rect",
          id: generateObjectId("cover_bg"),
          name: "Cover Background",
          left: 0, top: 0,
          width: w, height: h,
          fill: "#111612",
        },
        {
          type: "Rect",
          id: generateObjectId("cover_overlay"),
          name: "Cover Overlay",
          left: 0, top: 0,
          width: w, height: h,
          fill: "rgba(0,0,0,0.4)",
        },
        {
          type: "Textbox",
          id: generateObjectId("cover_eyebrow"),
          name: "Cover Eyebrow",
          text: "THE WEDDING OF",
          left: w / 2 - 120, top: h * 0.35,
          width: 240,
          fontSize: 12,
          fontFamily: "DM Sans",
          fill: "#C8B58A",
          textAlign: "center",
          charSpacing: 500,
        },
        {
          type: "Textbox",
          id: generateObjectId("cover_names"),
          name: "Cover Names",
          text: "Aral & Patricia",
          left: w / 2 - 180, top: h * 0.40,
          width: 360,
          fontSize: 52,
          fontFamily: "Cormorant Garamond",
          fill: "#F5F2EA",
          textAlign: "center",
        },
        {
          type: "Textbox",
          id: generateObjectId("cover_date"),
          name: "Cover Date",
          text: "24 . 08 . 2026",
          left: w / 2 - 100, top: h * 0.50,
          width: 200,
          fontSize: 14,
          fontFamily: "DM Sans",
          fill: "#D8D0BD",
          textAlign: "center",
          charSpacing: 300,
        },
      ],
    }),
  },
  {
    type: "couple-section",
    label: "Couple Section",
    icon: "💑",
    category: "wedding",
    create: (w, h) => ({
      type: "Group",
      id: generateObjectId("couple"),
      name: "Couple Section",
      _isPresetGroup: true,
      _children: [
        {
          type: "Textbox",
          id: generateObjectId("couple_label"),
          name: "Couple Label",
          text: "THE COUPLE",
          left: w / 2 - 100, top: 40,
          width: 200,
          fontSize: 11,
          fontFamily: "DM Sans",
          fill: "#C8B58A",
          textAlign: "center",
          charSpacing: 500,
        },
        {
          type: "Textbox",
          id: generateObjectId("couple_title"),
          name: "Couple Title",
          text: "Bride & Groom",
          left: w / 2 - 150, top: 65,
          width: 300,
          fontSize: 36,
          fontFamily: "Cormorant Garamond",
          fill: "#F5F2EA",
          textAlign: "center",
        },
        {
          type: "Circle",
          id: generateObjectId("bride_photo"),
          name: "Bride Photo",
          left: w / 2 - 130, top: 140,
          radius: 55,
          fill: "rgba(200,181,138,0.15)",
          stroke: "#C8B58A",
          strokeWidth: 1,
          data: { isImagePlaceholder: true, binding: "couple.bridePhoto" },
        },
        {
          type: "Circle",
          id: generateObjectId("groom_photo"),
          name: "Groom Photo",
          left: w / 2 + 20, top: 140,
          radius: 55,
          fill: "rgba(200,181,138,0.15)",
          stroke: "#C8B58A",
          strokeWidth: 1,
          data: { isImagePlaceholder: true, binding: "couple.groomPhoto" },
        },
        {
          type: "Textbox",
          id: generateObjectId("bride_name"),
          name: "Bride Name",
          text: "Patricia",
          left: w / 2 - 150, top: 265,
          width: 130,
          fontSize: 22,
          fontFamily: "Cormorant Garamond",
          fill: "#F5F2EA",
          textAlign: "center",
          data: { binding: "couple.bride" },
        },
        {
          type: "Textbox",
          id: generateObjectId("groom_name"),
          name: "Groom Name",
          text: "Aral",
          left: w / 2 + 20, top: 265,
          width: 130,
          fontSize: 22,
          fontFamily: "Cormorant Garamond",
          fill: "#F5F2EA",
          textAlign: "center",
          data: { binding: "couple.groom" },
        },
      ],
    }),
  },
  {
    type: "event-section",
    label: "Event Section",
    icon: "📅",
    category: "wedding",
    create: (w) => ({
      type: "Group",
      id: generateObjectId("event"),
      name: "Event Section",
      _isPresetGroup: true,
      _children: [
        {
          type: "Textbox",
          id: generateObjectId("event_label"),
          name: "Event Label",
          text: "SAVE THE DATE",
          left: w / 2 - 100, top: 40,
          width: 200,
          fontSize: 11,
          fontFamily: "DM Sans",
          fill: "#C8B58A",
          textAlign: "center",
          charSpacing: 500,
        },
        {
          type: "Textbox",
          id: generateObjectId("event_title"),
          name: "Event Title",
          text: "Wedding Event",
          left: w / 2 - 150, top: 65,
          width: 300,
          fontSize: 36,
          fontFamily: "Cormorant Garamond",
          fill: "#F5F2EA",
          textAlign: "center",
        },
        {
          type: "Textbox",
          id: generateObjectId("ceremony_title"),
          name: "Ceremony Title",
          text: "Akad Nikah",
          left: w / 2 - 120, top: 140,
          width: 240,
          fontSize: 20,
          fontFamily: "Cormorant Garamond",
          fill: "#F5F2EA",
          textAlign: "center",
        },
        {
          type: "Textbox",
          id: generateObjectId("ceremony_time"),
          name: "Ceremony Time",
          text: "08:00 – 10:00 WIB",
          left: w / 2 - 120, top: 170,
          width: 240,
          fontSize: 13,
          fontFamily: "DM Sans",
          fill: "#A8AEA4",
          textAlign: "center",
        },
        {
          type: "Textbox",
          id: generateObjectId("ceremony_venue"),
          name: "Ceremony Venue",
          text: "The Grand Ballroom, Jakarta",
          left: w / 2 - 120, top: 195,
          width: 240,
          fontSize: 13,
          fontFamily: "DM Sans",
          fill: "#A8AEA4",
          textAlign: "center",
        },
      ],
    }),
  },
  {
    type: "rsvp-section",
    label: "RSVP Section",
    icon: "✉️",
    category: "wedding",
    create: (w) => ({
      type: "Group",
      id: generateObjectId("rsvp"),
      name: "RSVP Section",
      _isPresetGroup: true,
      _children: [
        {
          type: "Textbox",
          id: generateObjectId("rsvp_label"),
          name: "RSVP Label",
          text: "KINDLY RESPOND",
          left: w / 2 - 100, top: 40,
          width: 200,
          fontSize: 11,
          fontFamily: "DM Sans",
          fill: "#C8B58A",
          textAlign: "center",
          charSpacing: 500,
        },
        {
          type: "Textbox",
          id: generateObjectId("rsvp_title"),
          name: "RSVP Title",
          text: "Are You Attending?",
          left: w / 2 - 150, top: 65,
          width: 300,
          fontSize: 36,
          fontFamily: "Cormorant Garamond",
          fill: "#F5F2EA",
          textAlign: "center",
        },
        {
          type: "Rect",
          id: generateObjectId("rsvp_form"),
          name: "RSVP Form Area",
          left: w / 2 - 160, top: 120,
          width: 320,
          height: 200,
          fill: "rgba(255,255,255,0.05)",
          stroke: "rgba(255,255,255,0.15)",
          strokeWidth: 1,
          rx: 12,
          ry: 12,
        },
      ],
    }),
  },
  {
    type: "gift-section",
    label: "Gift Section",
    icon: "🎁",
    category: "wedding",
    create: (w) => ({
      type: "Group",
      id: generateObjectId("gift"),
      name: "Gift Section",
      _isPresetGroup: true,
      _children: [
        {
          type: "Textbox",
          id: generateObjectId("gift_label"),
          name: "Gift Label",
          text: "WEDDING GIFT",
          left: w / 2 - 100, top: 40,
          width: 200,
          fontSize: 11,
          fontFamily: "DM Sans",
          fill: "#C8B58A",
          textAlign: "center",
          charSpacing: 500,
        },
        {
          type: "Textbox",
          id: generateObjectId("gift_title"),
          name: "Gift Title",
          text: "Your Presence Is Our\nGreatest Gift",
          left: w / 2 - 170, top: 65,
          width: 340,
          fontSize: 32,
          fontFamily: "Cormorant Garamond",
          fill: "#F5F2EA",
          textAlign: "center",
        },
        {
          type: "Rect",
          id: generateObjectId("gift_card1"),
          name: "Gift Account Card",
          left: w / 2 - 150, top: 160,
          width: 300,
          height: 80,
          fill: "rgba(255,255,255,0.05)",
          stroke: "rgba(200,181,138,0.3)",
          strokeWidth: 1,
          rx: 12,
          ry: 12,
        },
      ],
    }),
  },
  {
    type: "closing-section",
    label: "Closing Section",
    icon: "💌",
    category: "wedding",
    create: (w, h) => ({
      type: "Group",
      id: generateObjectId("closing"),
      name: "Closing Section",
      _isPresetGroup: true,
      _children: [
        {
          type: "Textbox",
          id: generateObjectId("closing_label"),
          name: "Closing Label",
          text: "WITH LOVE",
          left: w / 2 - 100, top: h * 0.35,
          width: 200,
          fontSize: 11,
          fontFamily: "DM Sans",
          fill: "#C8B58A",
          textAlign: "center",
          charSpacing: 500,
        },
        {
          type: "Textbox",
          id: generateObjectId("closing_title"),
          name: "Closing Title",
          text: "Thank You",
          left: w / 2 - 150, top: h * 0.40,
          width: 300,
          fontSize: 48,
          fontFamily: "Cormorant Garamond",
          fill: "#F5F2EA",
          textAlign: "center",
        },
        {
          type: "Textbox",
          id: generateObjectId("closing_names"),
          name: "Closing Names",
          text: "Aral & Patricia",
          left: w / 2 - 100, top: h * 0.50,
          width: 200,
          fontSize: 20,
          fontFamily: "Cormorant Garamond",
          fill: "#D8D0BD",
          textAlign: "center",
        },
      ],
    }),
  },
];

/**
 * Data binding variable definitions
 */
export const BINDING_VARIABLES = [
  { path: "couple.bride", label: "Nama Mempelai Wanita", type: "text" as const },
  { path: "couple.groom", label: "Nama Mempelai Pria", type: "text" as const },
  { path: "couple.brideFullName", label: "Nama Lengkap Wanita", type: "text" as const },
  { path: "couple.groomFullName", label: "Nama Lengkap Pria", type: "text" as const },
  { path: "couple.brideFather", label: "Ayah Mempelai Wanita", type: "text" as const },
  { path: "couple.brideMother", label: "Ibu Mempelai Wanita", type: "text" as const },
  { path: "couple.groomFather", label: "Ayah Mempelai Pria", type: "text" as const },
  { path: "couple.groomMother", label: "Ibu Mempelai Pria", type: "text" as const },
  { path: "couple.bridePhoto", label: "Foto Mempelai Wanita", type: "image" as const },
  { path: "couple.groomPhoto", label: "Foto Mempelai Pria", type: "image" as const },
  { path: "event.date", label: "Tanggal Acara", type: "date" as const },
  { path: "event.ceremony.time", label: "Waktu Akad", type: "text" as const },
  { path: "event.ceremony.venue", label: "Tempat Akad", type: "text" as const },
  { path: "event.ceremony.address", label: "Alamat Akad", type: "text" as const },
  { path: "event.reception.time", label: "Waktu Resepsi", type: "text" as const },
  { path: "event.reception.venue", label: "Tempat Resepsi", type: "text" as const },
  { path: "event.reception.address", label: "Alamat Resepsi", type: "text" as const },
  { path: "guest.name", label: "Nama Tamu", type: "text" as const },
  { path: "guest.parents", label: "Nama Orang Tua Tamu", type: "text" as const },
];
